import { Store, Product, StoreHours } from '@/types';

// Sample store hours (Monday - Sunday)
const defaultHours: StoreHours[] = [
  { day: 'Monday', open: '09:00', close: '21:00' },
  { day: 'Tuesday', open: '09:00', close: '21:00' },
  { day: 'Wednesday', open: '09:00', close: '21:00' },
  { day: 'Thursday', open: '09:00', close: '21:00' },
  { day: 'Friday', open: '09:00', close: '22:00' },
  { day: 'Saturday', open: '08:00', close: '22:00' },
  { day: 'Sunday', open: '10:00', close: '20:00' },
];

// Demo stores (using coordinates around Bangalore, India as example)
export const demoStores: Omit<Store, 'id'>[] = [
  {
    name: 'MegaMart Central',
    description: 'Large supermarket with wide variety of products',
    location: { lat: 12.9716, lng: 77.5946 },
    address: '123 MG Road, Bangalore, Karnataka 560001',
    phone: '+91 80 1234 5678',
    email: 'central@megamart.com',
    hours: defaultHours,
    inventory: [],
    rating: 4.5,
    reviewCount: 342,
    ownerId: 'demo-owner-1',
    categories: ['Groceries', 'Electronics', 'Home & Kitchen'],
    features: ['parking', 'wheelchair_accessible', 'air_conditioned'],
    lastInventoryUpdate: Date.now() - 2 * 60 * 60 * 1000, // 2 hours ago
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
  },
  {
    name: 'Fresh Mart Express',
    description: 'Your neighborhood fresh produce store',
    location: { lat: 12.9352, lng: 77.6245 },
    address: '456 Indiranagar, Bangalore, Karnataka 560038',
    phone: '+91 80 2345 6789',
    email: 'contact@freshmart.com',
    hours: defaultHours,
    inventory: [],
    rating: 4.2,
    reviewCount: 198,
    ownerId: 'demo-owner-2',
    categories: ['Groceries', 'Fresh Produce', 'Dairy'],
    features: ['parking', 'home_delivery'],
    lastInventoryUpdate: Date.now() - 1 * 60 * 60 * 1000, // 1 hour ago
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
  },
  {
    name: 'TechHub Store',
    description: 'Electronics and gadgets superstore',
    location: { lat: 12.9698, lng: 77.7499 },
    address: '789 Whitefield Road, Bangalore, Karnataka 560066',
    phone: '+91 80 3456 7890',
    email: 'support@techhub.com',
    hours: defaultHours,
    inventory: [],
    rating: 4.7,
    reviewCount: 567,
    ownerId: 'demo-owner-3',
    categories: ['Electronics', 'Mobile Phones', 'Computers'],
    features: ['parking', 'wifi', 'expert_assistance'],
    lastInventoryUpdate: Date.now() - 30 * 60 * 1000, // 30 minutes ago
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
  },
  {
    name: 'HomeStyle Essentials',
    description: 'Everything for your home',
    location: { lat: 12.9279, lng: 77.6271 },
    address: '321 Koramangala, Bangalore, Karnataka 560034',
    phone: '+91 80 4567 8901',
    email: 'info@homestyle.com',
    hours: defaultHours,
    inventory: [],
    rating: 4.3,
    reviewCount: 234,
    ownerId: 'demo-owner-4',
    categories: ['Home & Kitchen', 'Furniture', 'Decor'],
    features: ['parking', 'assembly_service'],
    lastInventoryUpdate: Date.now() - 4 * 60 * 60 * 1000, // 4 hours ago
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
  },
  {
    name: 'QuickStop Supermarket',
    description: 'Quick shopping for daily needs',
    location: { lat: 13.0358, lng: 77.5970 },
    address: '654 Yelahanka, Bangalore, Karnataka 560064',
    phone: '+91 80 5678 9012',
    email: 'hello@quickstop.com',
    hours: defaultHours,
    inventory: [],
    rating: 4.0,
    reviewCount: 145,
    ownerId: 'demo-owner-5',
    categories: ['Groceries', 'Snacks', 'Beverages'],
    features: ['parking', '24_hours'],
    lastInventoryUpdate: Date.now() - 6 * 60 * 60 * 1000, // 6 hours ago
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
  },
];

// Demo products
export const demoProducts: Omit<Product, 'id'>[] = [
  {
    name: 'Organic Whole Wheat Bread',
    description: 'Fresh baked whole wheat bread, 100% organic',
    category: 'Groceries',
    brand: 'NatureBake',
    basePrice: 45,
    tags: ['organic', 'bread', 'wheat', 'bakery'],
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Fresh Milk 1L',
    description: 'Farm fresh full cream milk',
    category: 'Dairy',
    brand: 'DairyFresh',
    basePrice: 60,
    tags: ['milk', 'dairy', 'fresh', 'organic'],
    createdAt: Date.now() - 25 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Samsung Galaxy Buds Pro',
    description: 'Premium wireless earbuds with active noise cancellation',
    category: 'Electronics',
    brand: 'Samsung',
    basePrice: 12999,
    tags: ['earbuds', 'wireless', 'audio', 'samsung'],
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Apple iPhone 15',
    description: 'Latest iPhone with advanced camera system',
    category: 'Mobile Phones',
    brand: 'Apple',
    basePrice: 79900,
    tags: ['iphone', 'smartphone', 'apple', 'premium'],
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Basmati Rice 5kg',
    description: 'Premium aged basmati rice',
    category: 'Groceries',
    brand: 'India Gate',
    basePrice: 450,
    tags: ['rice', 'basmati', 'groceries', 'staples'],
    createdAt: Date.now() - 40 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Colgate Total Toothpaste',
    description: 'Advanced protection toothpaste 150g',
    category: 'Personal Care',
    brand: 'Colgate',
    basePrice: 125,
    tags: ['toothpaste', 'oral care', 'hygiene'],
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Lenovo IdeaPad Laptop',
    description: 'Intel Core i5, 8GB RAM, 512GB SSD',
    category: 'Computers',
    brand: 'Lenovo',
    basePrice: 45999,
    tags: ['laptop', 'computer', 'lenovo', 'i5'],
    createdAt: Date.now() - 75 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Nescafe Classic Coffee',
    description: 'Instant coffee powder 100g',
    category: 'Beverages',
    brand: 'Nescafe',
    basePrice: 220,
    tags: ['coffee', 'instant', 'beverage', 'nescafe'],
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Prestige Pressure Cooker 5L',
    description: 'Stainless steel pressure cooker',
    category: 'Home & Kitchen',
    brand: 'Prestige',
    basePrice: 1899,
    tags: ['pressure cooker', 'kitchen', 'cookware'],
    createdAt: Date.now() - 50 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Britannia Good Day Cookies',
    description: 'Butter cookies pack of 250g',
    category: 'Snacks',
    brand: 'Britannia',
    basePrice: 50,
    tags: ['cookies', 'snacks', 'biscuits', 'britannia'],
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Dove Soap Bar',
    description: 'Moisturizing beauty bar 100g',
    category: 'Personal Care',
    brand: 'Dove',
    basePrice: 55,
    tags: ['soap', 'bath', 'beauty', 'dove'],
    createdAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Amul Butter 500g',
    description: 'Pure butter made from fresh cream',
    category: 'Dairy',
    brand: 'Amul',
    basePrice: 280,
    tags: ['butter', 'dairy', 'amul', 'spread'],
    createdAt: Date.now() - 18 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Sony Bravia 55" 4K TV',
    description: 'Smart LED TV with Android',
    category: 'Electronics',
    brand: 'Sony',
    basePrice: 65999,
    tags: ['tv', 'smart tv', 'sony', '4k', 'led'],
    createdAt: Date.now() - 80 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Lays Classic Chips',
    description: 'Salted potato chips 90g',
    category: 'Snacks',
    brand: 'Lays',
    basePrice: 40,
    tags: ['chips', 'snacks', 'lays', 'potato'],
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
  {
    name: 'Tata Tea Gold',
    description: 'Premium tea leaves 500g',
    category: 'Beverages',
    brand: 'Tata',
    basePrice: 235,
    tags: ['tea', 'beverage', 'tata', 'leaves'],
    createdAt: Date.now() - 22 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
  },
];

// Function to seed inventory for stores
export function generateInventory(productIds: string[]) {
  return productIds.map((productId, index) => ({
    productId,
    quantity: Math.floor(Math.random() * 50) + 10, // 10-60 items
    price: demoProducts[index % demoProducts.length].basePrice + Math.floor(Math.random() * 20) - 10,
    lastUpdated: Date.now() - Math.floor(Math.random() * 24 * 60 * 60 * 1000),
    lowStockThreshold: 5,
  }));
}
